apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shipping-api-ingress
  labels:
    name: shipping-api-ingress
spec:
  rules:
  - host: api.company.com
    https:
      - paths:
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: shipping-service
            port: 
              number: 80
