@Software.Api_HostAddress = http://localhost:1337

POST {{Software.Api_HostAddress}}/catalog
Content-Type: application/json

{
    "title": "Bozo",
    "vendor": "Dirtbag",
    "isOpenSource": false
}

###

GET {{Software.Api_HostAddress}}/open-source-software
