services:

  shipping:
    image: jeffrygonzalez/shipping-api-oct-2024:v1.0
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8080:8080
  db:
    image: postgres:16.2-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 5439:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    environment:
      ADMINER_DESIGN: dracula
volumes:
  db_data: